### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by NathanWind** [Syntonie/documentation#1]
Visualist_OG_RevA_Gerbers.rar file is damaged.

**Comment by Syntonie** [comment]
Thanks for reporting, what is the exact issue? Because I'm able to unnzip the archive and I also upload it to pcb fab service and there is no error.

**Comment by NathanWind** [comment]
> Thanks for reporting, what is the exact issue? Because I'm able to unnzip the archive and I also upload it to pcb fab service and there is no error.

Thanks for the reply. I've downloaded multiple times and says "the archive is either unknown format or damaged". I fixed it using 7-zip instead of winrar.

**Comment by Syntonie** [comment]
I've put put the unzipped gerbers directly so it's easier. Thanks again for reporting
