### ISSUE TITLE
broken .csv encoding

### ISSUE THREAD

**Issue by Jackson-Devices** [Syntonie/documentation#2]
VU002_RevD_BOM.csv has UTF-7 encoding.  It does not appear in tables in github like your other .csv files and didn't open corectly in microsoft excel without going in and manually changing UTF-7 encoded quotation marks.  There are quite a few others to change for - and _ symbols.  I could do a pull request if you want, as I have fixed my locally saved copy

**Comment by Syntonie** [comment]
Thanks for letting me know, just updated the file with the right encoding this time.
